package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	ADD_FILE, BACKUP_FILE, REMOVE_FILE, VIEW_FILES, FILES,
	ADD_FRIEND,
	REQUEST_TOKEN, TOKEN, UPDATE_FINISH
}
